export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED  = 'LOGIN_FAILED';

export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILED  = 'SIGNUP_FAILED';

export const NEW_SERVICES_REQUEST = 'NEW_SERVICES_REQUEST';
export const NEW_SERVICES_SUCCESS = 'NEW_SERVICES_SUCCESS';
export const NEW_SERVICES_ERROR  = 'NEW_SERVICES_ERROR';

export const GETTING_USER_FROM_STORAGE  = 'GETTING_USER_FROM_STORAGE';
export const GOT_USER_FROM_STORAGE  = 'GOT_USER_FROM_STORAGE';

export const ADD_INFLUENCER_TO_CART  = 'ADD_INFLUENCER_TO_CART';
export const REMOVE_INFLUENCER_FROM_CART  = 'REMOVE_INFLUENCER_FROM_CART';
export const ADD_SERVICE_TO_CART  = 'ADD_SERVICE_TO_CART';
export const PROCESS_CART  = 'PROCESS_CART';
export const EMPTY_THE_CART  = 'EMPTY_THE_CART';

export const CREATE_SERVICE_REQUEST  = 'CREATE_SERVICE_REQUEST';

export const SERVICE_IMAGE_REQUEST  = 'SERVICE_IMAGE_REQUEST';
export const SERVICE_IMAGE_SUCCESS  = 'SERVICE_IMAGE_SUCCESS';
export const SERVICE_IMAGE_FAILED  = 'SERVICE_IMAGE_FAILED';

export const GET_INFLUENCERS_REQUEST= 'GET_INFLUENCERS_REQUEST';
export const REFRESH_INFLUENCERS_REQUEST= 'REFRESH_INFLUENCERS_REQUEST';
export const GOT_INFLUENCERS= 'GOT_INFLUENCERS';
export const INFLUENCERS_REQUEST_FAILED= 'INFLUENCERS_REQUEST_FAILED';

export const SENDING_SERVICE_REQUEST  = 'SENDING_SERVICE_REQUEST';
export const SERVICE_REQUEST_SUCCES  = 'SERVICE_REQUEST_SUCCES';
export const SERVICE_REQUEST_FAILED  = 'SERVICE_REQUEST_FAILED';


export const MY_SERVICES_SUCCESS  = 'MY_SERVICES_SUCCESS';
export const MY_SERVICES_REQUEST  = 'MY_SERVICES_REQUEST';
export const MY_SERVICES_ERROR  = 'MY_SERVICES_ERROR';

export const ACCEPT_OR_REJECT_SERVICE  = 'ACCEPT_OR_REJECT_SERVICE';

export const REVIEW_SUCCESS  = 'REVIEW_SUCCESS';
export const REVIEW_REQUEST  = 'REVIEW_REQUEST';
export const REVIEW_ERROR  = 'REVIEW_ERROR';


export const GOT_NEW_NOTIFICATION  = 'GOT_NEW_NOTIFICATION';

export const RESET_EVERYTHING  = 'RESET_EVERYTHING';

export const ADD_NAVIGATOR  = 'ADD_NAVIGATOR';



